// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sidebar/CardPills.tsx": () => import("../components/mockups/sidebar/CardPills.tsx"),
  "./components/mockups/sidebar/Current.tsx": () => import("../components/mockups/sidebar/Current.tsx"),
  "./components/mockups/sidebar/Floating.tsx": () => import("../components/mockups/sidebar/Floating.tsx"),
  "./components/mockups/sidebar/Minimal.tsx": () => import("../components/mockups/sidebar/Minimal.tsx"),
  "./components/mockups/student-profile/Current.tsx": () => import("../components/mockups/student-profile/Current.tsx"),
  "./components/mockups/student-profile/SidebarDense.tsx": () => import("../components/mockups/student-profile/SidebarDense.tsx"),
  "./components/mockups/student-profile/Tabbed.tsx": () => import("../components/mockups/student-profile/Tabbed.tsx"),
  "./components/mockups/student-profile/Timeline.tsx": () => import("../components/mockups/student-profile/Timeline.tsx"),
  "./components/mockups/submission-form/MultiStep.tsx": () => import("../components/mockups/submission-form/MultiStep.tsx")
};
