// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sidebar/CardPills.tsx": () => import("../components/mockups/sidebar/CardPills.tsx"),
  "./components/mockups/sidebar/Current.tsx": () => import("../components/mockups/sidebar/Current.tsx"),
  "./components/mockups/sidebar/Floating.tsx": () => import("../components/mockups/sidebar/Floating.tsx"),
  "./components/mockups/sidebar/Minimal.tsx": () => import("../components/mockups/sidebar/Minimal.tsx"),
  "./components/mockups/student-profile/CompactBanner.tsx": () => import("../components/mockups/student-profile/CompactBanner.tsx"),
  "./components/mockups/student-profile/Current.tsx": () => import("../components/mockups/student-profile/Current.tsx"),
  "./components/mockups/student-profile/DashboardTiles.tsx": () => import("../components/mockups/student-profile/DashboardTiles.tsx"),
  "./components/mockups/student-profile/SidebarDense.tsx": () => import("../components/mockups/student-profile/SidebarDense.tsx"),
  "./components/mockups/student-profile/SidebarLayout.tsx": () => import("../components/mockups/student-profile/SidebarLayout.tsx"),
  "./components/mockups/student-profile/Tabbed.tsx": () => import("../components/mockups/student-profile/Tabbed.tsx"),
  "./components/mockups/student-profile/Timeline.tsx": () => import("../components/mockups/student-profile/Timeline.tsx"),
  "./components/mockups/student-profile-edit/EditAccessibility.tsx": () => import("../components/mockups/student-profile-edit/EditAccessibility.tsx"),
  "./components/mockups/student-profile-edit/EditAffordances.tsx": () => import("../components/mockups/student-profile-edit/EditAffordances.tsx"),
  "./components/mockups/student-profile-edit/EditHierarchy.tsx": () => import("../components/mockups/student-profile-edit/EditHierarchy.tsx"),
  "./components/mockups/student-profile-edit/EditInlineDense.tsx": () => import("../components/mockups/student-profile-edit/EditInlineDense.tsx"),
  "./components/mockups/student-profile-edit/EditSplitPanel.tsx": () => import("../components/mockups/student-profile-edit/EditSplitPanel.tsx"),
  "./components/mockups/student-profile-edit/EditStepped.tsx": () => import("../components/mockups/student-profile-edit/EditStepped.tsx"),
  "./components/mockups/submission-form/MultiStep.tsx": () => import("../components/mockups/submission-form/MultiStep.tsx"),
  "./components/mockups/uni-mobile/AvatarList.tsx": () => import("../components/mockups/uni-mobile/AvatarList.tsx"),
  "./components/mockups/uni-mobile/CardGrid.tsx": () => import("../components/mockups/uni-mobile/CardGrid.tsx"),
  "./components/mockups/uni-mobile/FeaturedScroll.tsx": () => import("../components/mockups/uni-mobile/FeaturedScroll.tsx")
};
