// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/student-profile/Current.tsx": () => import("../components/mockups/student-profile/Current.tsx"),
  "./components/mockups/student-profile/SidebarDense.tsx": () => import("../components/mockups/student-profile/SidebarDense.tsx"),
  "./components/mockups/student-profile/Tabbed.tsx": () => import("../components/mockups/student-profile/Tabbed.tsx"),
  "./components/mockups/student-profile/Timeline.tsx": () => import("../components/mockups/student-profile/Timeline.tsx")
};
