export const clerkLightAppearance = {
  variables: {
    colorPrimary: "#851651",
    colorBackground: "#ffffff",
    colorForeground: "#0f0a0d",
    colorMutedForeground: "#6b7280",
    colorDanger: "#b3402f",
    colorInput: "#ffffff",
    colorInputForeground: "#0f0a0d",
    colorNeutral: "#6b1140",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full rounded-xl overflow-hidden",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none",
    footer: "!shadow-none !border-0 !bg-transparent !rounded-none",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    formFieldLabel: "text-foreground",
    formFieldInput: "bg-white border-border text-foreground",
    formButtonPrimary: "bg-[#851651] hover:bg-[#6b1140] text-white",
    footerActionText: "text-muted-foreground",
    footerActionLink: "text-[#851651] hover:text-[#6b1140]",
    dividerText: "text-muted-foreground",
    dividerLine: "bg-border",
    socialButtonsBlockButtonText: "text-foreground",
    identityPreviewEditButton: "text-[#851651]",
    formFieldSuccessText: "text-green-600",
    alertText: "text-foreground",
    alert: "bg-destructive/10 border-destructive/30",
    otpCodeFieldInput: "bg-white border-border text-foreground",
    footerAction: "bg-transparent",
    logoBox: "hidden",
    main: "",
    formFieldRow: "",
    socialButtonsBlockButton: "border-border bg-white hover:bg-muted",
    profileSection__danger: { display: "none" },
    profileSectionHeader__danger: { display: "none" },
    profileSectionContent__danger: { display: "none" },
    profileSectionItemList__danger: { display: "none" },
  },
};
